import datetime
import logging
from typing import Any

from langchain_core.documents import Document
from pymilvus import AnnSearchRequest, DataType, Function, FunctionType, MilvusClient, RRFRanker, model

from apps.config import settings

logger = logging.getLogger(__name__)


class MilvusVector:
    collection_name = "document_embedding"

    def __init__(self, url: str, token: str, db_name: str):
        self.init_database(url=url, token=token, db_name=db_name)
        self.client = MilvusClient(uri=url, token=token, db_name=db_name)
        self.init_collection()
        self.openai_ef = model.dense.OpenAIEmbeddingFunction(
            model_name=settings.EMBEDDING_MODEL, api_key=settings.OPENAI_API_KEY, dimensions=1024
        )

    def init_database(self, url: str, token: str, db_name: str) -> None:
        """Init database."""
        client = MilvusClient(uri=url, token=token)
        if db_name in client.list_databases():
            return

        client.create_database(db_name=db_name, properties={"timezone": "Asia/Shanghai"})
        logger.info(f"Create database: {db_name}")

    def init_collection(self) -> None:
        """Init collection."""

        if self.client.has_collection(collection_name=self.collection_name):
            return

        schema = MilvusClient.create_schema(
            auto_id=True,
            enable_dynamic_field=True,
        )

        # 文本匹配Analyzer
        analyzer_params = {"type": "chinese"}

        # 创建字段
        schema.add_field(
            field_name="id", datatype=DataType.INT64, is_primary=True, auto_id=True, description="primary id"
        )
        schema.add_field(field_name="user_id", datatype=DataType.VARCHAR, max_length=64, description="knowledge id")
        schema.add_field(field_name="knowledge_id", datatype=DataType.INT64, description="knowledge id")
        schema.add_field(field_name="file_id", datatype=DataType.INT64, description="document id")
        schema.add_field(
            field_name="document_text",
            datatype=DataType.VARCHAR,
            max_length=1000,
            enable_analyzer=True,
            enable_match=True,
            analyzer_params=analyzer_params,
            description="raw text of document",
        )
        schema.add_field(
            field_name="metadata", datatype=DataType.JSON, nullable=True, description="metadata of document"
        )
        schema.add_field(
            field_name="text_dense", datatype=DataType.FLOAT_VECTOR, dim=1024, description="text dense embedding"
        )
        schema.add_field(
            field_name="text_sparse",
            datatype=DataType.SPARSE_FLOAT_VECTOR,
            description="text sparse embedding auto-generated by the built-in BM25 function",
        )
        schema.add_field(field_name="create_time", datatype=DataType.INT64, description="create time")

        # 创建BM25函数
        bm25_function = Function(
            name="text_bm25_emb",
            input_field_names=["document_text"],
            output_field_names=["text_sparse"],
            function_type=FunctionType.BM25,
        )
        schema.add_function(bm25_function)

        # 创建索引
        index_params = self.client.prepare_index_params()
        index_params.add_index(
            field_name="text_dense",
            index_name="text_dense_index",
            index_type="AUTOINDEX",  # 自动索引类型,允许 Milvus 自动优化索引设置
        )
        index_params.add_index(
            field_name="text_sparse",
            index_name="text_sparse_index",
            index_type="SPARSE_INVERTED_INDEX",  # 倒排索引原理
            metric_type="BM25",
            params={"inverted_index_algo": "DAAT_MAXSCORE"},  # or "DAAT_WAND" or "TAAT_NAIVE"
        )

        # 创建collection
        self.client.create_collection(collection_name=self.collection_name, schema=schema, index_params=index_params)

        res = self.client.get_load_state(collection_name=self.collection_name)

        logger.info("Create collection: %s", res)

    def save_documents(self, docs: list[Document], user_id: str, knowledge_id: int, file_id: int) -> None:
        if not docs:
            return

        # 批量生成 embeddings
        docs_embeddings = self.openai_ef.encode_documents([doc.page_content for doc in docs])

        # 动态生成 data 列表
        data = [
            {
                "user_id": user_id,
                "knowledge_id": knowledge_id,
                "file_id": file_id,
                "document_text": doc.page_content,
                "text_dense": embedding,
                "metadata": doc.metadata or {},
                "create_time": int(datetime.datetime.now().timestamp() * 1000),
            }
            for doc, embedding in zip(docs, docs_embeddings, strict=True)
        ]

        res = self.client.insert(collection_name=self.collection_name, data=data)
        logger.info("res: %s, 插入 %d 条数据成功", res, len(docs))

    def vector_search(self, query: str, user_id: str, knowledge_id: int = 1, top_k: int = 3) -> list[dict[str, Any]]:
        """向量搜索"""

        # 创建查询条件
        query_embeddings = self.openai_ef.encode_queries([query])
        # 创建查询参数
        result = self.client.search(
            collection_name=self.collection_name,
            anns_field="text_dense",
            data=query_embeddings,
            filter=f'user_id == "{user_id}" and knowledge_id == {knowledge_id}',
            limit=top_k,
            output_fields=["id", "document_text"],
        )
        return [hit["entity"] for hits in result for hit in hits]

    def hybrid_search(self, query: str, user_id: str, knowledge_id: int = 1, top_k: int = 3) -> list[dict[str, Any]]:
        """混合搜索"""

        # 创建查询条件
        query_embeddings = self.openai_ef.encode_queries([query])
        # 语义搜索
        semantic_search_param = {
            "data": query_embeddings,
            "anns_field": "text_dense",
            "param": {
                "nprobe": 10
            },  # 搜索候选集群的集群数。数值越大，搜索的簇数越多，搜索范围越大，召回率越高，但代价是查询延迟增加。
            "expr": f'user_id == "{user_id}" and knowledge_id == {knowledge_id}',
            "limit": top_k,
        }
        semantic_search_request = AnnSearchRequest(**semantic_search_param)
        # 全文搜索
        full_text_search_param = {
            "data": [query],
            "anns_field": "text_sparse",
            "param": {},  # BM25 搜索不需要额外参数
            "expr": f'user_id == "{user_id}" and knowledge_id == {knowledge_id}',
            "limit": top_k,
        }
        full_text_search_request = AnnSearchRequest(**full_text_search_param)

        # 使用 dense 向量搜索和 sparse (BM25) 搜索
        reqs = [semantic_search_request, full_text_search_request]
        # 创建 ranker
        ranker = RRFRanker(100)

        result = self.client.hybrid_search(
            collection_name=self.collection_name,
            reqs=reqs,
            ranker=ranker,
            output_fields=["id", "document_text"],
            limit=top_k,
        )
        return [hit["entity"] for hits in result for hit in hits]

    def text_match(
        self, query: str, keyword: str, user_id: str, knowledge_id: int = 1, limit: int = 3
    ) -> list[dict[str, Any]]:
        """文本匹配与向量相似性搜索结合使用，以缩小搜索范围并提高搜索性能。"""
        filter = f'user_id == "{user_id}" and knowledge_id == {knowledge_id} and TEXT_MATCH(document_text, "{keyword}")'
        query_vector = self.openai_ef.encode_queries([query])
        result = self.client.search(
            collection_name=self.collection_name,
            anns_field="text_dense",
            data=query_vector,
            filter=filter,
            search_params={"params": {"nprobe": 10}},
            limit=limit,
            output_fields=["id", "document_text"],
        )
        return [hit["entity"] for hits in result for hit in hits]

    def delete_documents(self, file_id: int, user_id: str, knowledge_id: int = 1) -> None:
        filter = f'file_id == {file_id} and user_id == "{user_id}" and knowledge_id == {knowledge_id}'
        res = self.client.delete(collection_name=self.collection_name, filter=filter)
        logger.info("Delete data: %s", res)


milvus_vector = MilvusVector(db_name=settings.MILVUS_DB_NAME, token=settings.MILVUS_TOKEN, url=settings.MILVUS_URL)

if __name__ == "__main__":
    # client = MilvusClient(uri="http://172.16.100.160:19530", token="root:Milvus", db_name="buddy_ai")
    # res = client.drop_collection(collection_name="document_embedding")
    # print("Drop collection: ", res)
    # client.drop_collection(collection_name="mem0")
    # client.drop_collection(collection_name="mem0migrations")
    # client.drop_database(
    #     db_name="buddy_ai"
    # )
    data = [
        "人工智能是计算机科学的一个分支，致力于开发能够执行通常需要人类智能的任务的系统。这包括视觉感知、语音识别、决策制定和语言翻译等。",
        "机器学习是从大量数据里找规律，它通过训练模型来从数据中提取特征，并使用这些特征来预测未知数据。",
        "列表推导式：用一条简洁语句，从可迭代对象中，生成新列表的语法结构。",
        "函数式编程：将函数作为参数传递给其他函数，或者将函数作为返回值。",
        "闭包：当一个内部函数中访问了外部函数的局部变量，并且这个内部函数在外部被返回或调用时，就形成了闭包。",
        "AI是人工智能。",
    ]
    document_list = [Document(page_content=text) for text in data]
    milvus_vector.save_documents(document_list, "1", 1, 1)
    res = milvus_vector.hybrid_search("什么是人工智能", "1", 1)
    print("hybrid_search: ", res)
    res = milvus_vector.text_match("什么是人工智能", "人工智能", "1", 1)
    print("text_match: ", res)
